In [1]:
import Bounds as bds
import Bound as bd
import Table as tbl
import UpperBounds as ubds
import LowerBounds as lbds
import Robinson as Rob
import numpy as np

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
a = bd.Bound(ds = [1,2,3])
print(a)
b = bd.Bound(None,toCpy=a)
print("b: ", b)
d = a+b

c = (a+b).cpy()
print(a,c)

print(a <= c)
print(a >= c)

[1 2 3]
b:  [1 2 3]
[1 2 3] [2 4 6]
True
False


In [3]:
a3 = bd.Bound(ds= [2,4])
a2 = bd.Bound(ds= [3,2])
a1 = bd.Bound(ds =[2,2])
A_ = bds.Bounds()

A = lbds.LowerBounds(A_)
A.union(a1)
A.union(a2)
print(A)
B = lbds.LowerBounds(toCpy=A)
B.union(a3)
print(B)
#C = A.oMinusU(B)
#D = A.oPlusU(B)
#print(C, D)

{[3 2]}
{[3 2],[2 4]}


In [4]:
a1 = bd.Bound(ds= [2,4])
a2 = bd.Bound(ds= [3,2])
a3 = bd.Bound(ds =[2,2])
A = lbds.LowerBounds()
A.union(a1)
A.union(a2)
print(A)
B = ubds.UpperBounds()
B.union(a3)
print(B)
C = A - (B)
D = A + (B)
print(C, D)

{[2 4],[3 2]}
{[2 2]}
{[0 2],[1 0]} {[4 6],[5 4]}


In [5]:
T = [[A, B, C],
[None, B, C],
[None, None, C],
]

T = tbl.Table(withArray= T)

T.joinBoundsAt(0,0, D)
print(T)
len(T)
print(T.TypeTable())
# T + T

(0,0): {[4 6],[5 4]}	(0,1): {[2 2]}	(0,2): {[0 2],[1 0]}	
(1,0): {[2 2]}	(1,1): {[2 2]}	(1,2): {[0 2],[1 0]}	
(2,0): {[0 2],[1 0]}	(2,1): {[0 2],[1 0]}	(2,2): {[0 2],[1 0]}	

LowerBounds	UpperBounds	LowerBounds	
UpperBounds	UpperBounds	LowerBounds	
LowerBounds	LowerBounds	LowerBounds	



In [6]:
a = np.array([12,3,4])
print(a)
b = np.array(a)
print(b+1)
len(b)

[12  3  4]
[13  4  5]


3

In [7]:
class Test:
  def __init__(self):
    self.n = 3
  def __len__(self):
    return 7
  def dim(self):
    return 12

In [8]:
T = []
if not isinstance(T, list):
    
    raise Exception("withArray variable expects list, "+str(type(T))+" given.")


In [13]:
G = [ [ 2, 2, 1, 0, 0, 0 ],
      [ 2, 2, 2, 1, 1, 1 ],
      [ 1, 2, 2, 2, 1, 1 ],
      [ 0, 1, 2, 2, 2, 1 ],
      [ 0, 1, 1, 2, 2, 2 ],
      [ 0, 1, 1, 1, 2, 2 ] ]
R = Rob.Robinson(G,  k = 2)
R.find_embedding()

Within table
 (0,0): {[0 1],[ 1 -1]}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 0]}	(0,4): {[1 1]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {[0 1],[ 1 -1]}	(1,2): {[0 1],[ 1 -1]}	(1,3): {[0 2],[ 1 -1]}	(1,4): {[1 0]}	(1,5): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1],[ 1 -1]}	(2,2): {[0 1],[ 1 -1]}	(2,3): {[0 1],[ 1 -1]}	(2,4): {[1 0],[0 2]}	(2,5): {[1 0]}	
(3,0): {[1 0]}	(3,1): {[0 2],[ 1 -1]}	(3,2): {[0 1],[ 1 -1]}	(3,3): {[0 1],[ 1 -1]}	(3,4): {[0 1],[ 1 -1]}	(3,5): {[0 1],[ 1 -1]}	
(4,0): {[1 1]}	(4,1): {[1 0]}	(4,2): {[1 0],[0 2]}	(4,3): {[0 1],[ 1 -1]}	(4,4): {[0 1],[ 1 -1]}	(4,5): {[0 1],[ 1 -1]}	
(5,0): {[1 1]}	(5,1): {[1 0]}	(5,2): {[1 0]}	(5,3): {[0 1],[ 1 -1]}	(5,4): {[0 1],[ 1 -1]}	(5,5): {[0 1],[ 1 -1]}	
 
Away table
 (0,0): {[0 0]}	(0,1): {[0 1]}	(0,2): {[0 1],[ 1 -1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {[0 0],[-1  2]}	(1,2): {[0 0],[-1  2]}	(1,3): {[0 1],[ 1 -1]}	(1,4): {[0 1],[ 1 -1]}	(1,5): {[0 2],[1 0]}	
(2,0): {[0 1],[ 1 -1]}	(

In [16]:
G = [ [ 2, 2, 1, 0, 0 ],
      [ 2, 2, 2, 1, 1 ],
      [ 1, 2, 2, 2, 1 ],
      [ 0, 1, 2, 2, 2 ],
      [ 0, 1, 1, 2, 2 ] ]
R = Rob.Robinson(G,  k = 2)
R.find_embedding()

Within table
 (0,0): {[0 1],[ 1 -1]}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 1]}	(0,4): {[1 1]}	
(1,0): {[0 1]}	(1,1): {[0 1],[ 1 -1]}	(1,2): {[0 1],[ 1 -1]}	(1,3): {[1 0],[0 2]}	(1,4): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1],[ 1 -1]}	(2,2): {[0 1],[ 1 -1]}	(2,3): {[0 1]}	(2,4): {[1 0],[0 2]}	
(3,0): {[1 1]}	(3,1): {[1 0],[0 2]}	(3,2): {[0 1]}	(3,3): {[0 1],[ 1 -1]}	(3,4): {[0 1],[ 1 -1]}	
(4,0): {[1 1]}	(4,1): {[1 0]}	(4,2): {[1 0],[0 2]}	(4,3): {[0 1],[ 1 -1]}	(4,4): {[0 1],[ 1 -1]}	
 
Away table
 (0,0): {[0 0]}	(0,1): {[0 0],[-1  2]}	(0,2): {[0 1],[ 1 -1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	
(1,0): {[0 0],[-1  2]}	(1,1): {[0 0]}	(1,2): {[0 0]}	(1,3): {[0 1],[ 1 -1]}	(1,4): {[0 1],[ 1 -1]}	
(2,0): {[0 1],[ 1 -1]}	(2,1): {[0 0]}	(2,2): {[0 0]}	(2,3): {[0 0]}	(2,4): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1],[ 1 -1]}	(3,2): {[0 0]}	(3,3): {[0 0]}	(3,4): {[0 0]}	
(4,0): {[1 0],[0 2]}	(4,1): {[0 1],[ 1 -1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {[0 0]}	

-------iter  1  ends-----
W

Within table
 (0,0): {[0 1],[ 1 -1],[-1  3],[-2  6],[-3  9],[-4 12],[-5 15],[-6 18],[-7 21],[-8 24],[-9 27],[-10  30],[-11  33],[-12  36],[-13  39],[-14  42],[-15  45],[-16  48],[-17  51],[-18  54],[-19  57],[-20  60],[-21  63],[-22  66],[-23  69],[-24  72],[-25  78],[-26  84]}	(0,1): {[0 1],[-1  4],[-2  7],[-3 10],[-4 13],[-5 16],[-6 19],[-7 22],[-8 25],[-9 28],[-10  31],[-11  34],[-12  37],[-13  40],[-14  43],[-15  46],[-16  49],[-17  52],[-18  55],[-19  58],[-20  61],[-21  64],[-22  67],[-23  70],[-24  74],[-25  78],[-26  84]}	(0,2): {[1 0],[0 2],[-1  5],[-2  8],[-3 11],[-4 14],[-5 17],[-6 20],[-7 23],[-8 26],[-9 29],[-10  32],[-11  35],[-12  38],[-13  41],[-14  44],[-15  47],[-16  50],[-17  53],[-18  56],[-19  59],[-20  62],[-23  72],[-21  65],[-22  68],[-24  75],[-25  80],[-26  86]}	(0,3): {[1 1],[0 3],[-1  6],[-2  9],[-3 12],[-4 15],[-5 18],[-6 21],[-7 24],[-8 27],[-9 30],[-10  33],[-11  36],[-12  39],[-15  49],[-13  42],[-14  45],[-16  52],[-17  55],[-18  58],[-19  61],[-20  64]

-------iter  5  ends-----
Within table
 (0,0): {[0 1],[ 1 -1],[-1  3],[-2  6],[-3  9],[-4 12],[-5 15],[-6 18],[-7 21],[-8 24],[-9 27],[-10  30],[-11  33],[-12  36],[-13  39],[-14  42],[-15  45],[-16  48],[-17  51],[-18  54],[-19  57],[-20  60],[-21  63],[-22  66],[-23  69],[-24  72],[-25  75],[-26  78],[-27  81],[-28  84],[-29  87],[-30  90],[-31  93],[-32  96],[-33  99],[-34 102],[-35 105],[-36 108],[-37 111],[-38 114],[-39 117],[-40 120],[-41 123],[-42 126],[-43 129],[-44 132],[-45 135],[-46 138],[-47 141],[-48 144],[-49 147],[-50 150],[-51 153],[-52 156],[-53 159],[-54 162],[-55 165],[-56 168],[-57 171],[-58 174],[-59 177],[-60 180],[-61 183],[-62 186],[-63 189],[-64 192],[-65 195],[-66 198],[-67 201],[-68 204],[-69 207],[-70 210],[-71 214],[-72 218],[-74 226],[-73 221],[-75 231],[-76 236],[-77 241],[-78 247],[-79 253],[-80 260]}	(0,1): {[0 1],[-1  4],[-2  7],[-3 10],[-4 13],[-5 16],[-6 19],[-7 22],[-8 25],[-9 28],[-10  31],[-11  34],[-12  37],[-13  40],[-14  43],[-15  46],[-16  49]

 (0,0): {[0 0],[ 1 -3],[ 2 -6],[ 3 -9],[  4 -12],[  5 -15],[  6 -18],[  7 -21],[  8 -24],[  9 -27],[ 10 -30],[ 11 -33],[ 12 -36],[ 13 -39],[ 14 -42],[ 15 -45],[ 16 -48],[ 17 -51],[ 18 -54],[ 19 -57],[ 20 -60],[ 21 -63],[ 22 -66],[ 23 -69],[ 24 -72],[ 25 -75],[ 26 -78],[ 27 -81],[ 28 -84],[ 29 -87],[ 30 -90],[ 31 -93],[ 32 -96],[ 33 -99],[  34 -102],[  35 -105],[  36 -108],[  37 -111],[  38 -114],[  39 -117],[  40 -120],[  41 -123],[  42 -126],[  43 -129],[  44 -132],[  45 -135],[  46 -138],[  47 -141],[  48 -144],[  49 -147],[  50 -150],[  51 -153],[  52 -156],[  53 -159],[  54 -162],[  55 -165],[  56 -168],[  57 -171],[  58 -174],[  59 -177],[  60 -180],[  61 -183],[  62 -186],[  63 -189],[  64 -192],[  65 -195],[  66 -198],[  67 -201],[  68 -204],[  69 -207],[  70 -210],[  71 -214],[  72 -218],[  74 -226],[  73 -221],[  75 -231],[  76 -236],[  77 -241],[  78 -247],[  79 -253],[  80 -260]}	(0,1): {[0 0],[-1  2],[ 1 -2],[ 2 -5],[ 3 -8],[  4 -11],[  5 -14],[  6 -17],[  7 -20],[  8 -23],

-------iter  6  ends-----


KeyboardInterrupt: 

In [15]:
L1 = R.L_at(0)
U1 = R.U_at(0)
print("Lower:\n"+ str(R.L_at(0)))
#print(R.L_at(0).TypeTable())
print("Upper:\n", R.U_at(0))
#print(R.U_at(0).TypeTable())

L1 = R.L_at(1)
U1 = R.U_at(1)
print("Lower 1:\n"+ str(R.L_at(1)))
#print(R.L_at(0).TypeTable())
print("Upper 1:\n", R.U_at(1))
#print(R.U_at(0).TypeTable())

Lower:
(0,0): {[0 0]}	(0,1): {[0 0]}	(0,2): {[0 1]}	(0,3): {[1 0]}	(0,4): {[1 0]}	(0,5): {[1 0]}	
(1,0): {[0 0]}	(1,1): {[0 0]}	(1,2): {[0 0]}	(1,3): {[0 1]}	(1,4): {[0 1]}	(1,5): {[0 1]}	
(2,0): {[0 1]}	(2,1): {[0 0]}	(2,2): {[0 0]}	(2,3): {[0 0]}	(2,4): {[0 1]}	(2,5): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1]}	(3,2): {[0 0]}	(3,3): {[0 0]}	(3,4): {[0 0]}	(3,5): {[0 1]}	
(4,0): {[1 0]}	(4,1): {[0 1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {[0 0]}	(4,5): {[0 0]}	
(5,0): {[1 0]}	(5,1): {[0 1]}	(5,2): {[0 1]}	(5,3): {[0 1]}	(5,4): {[0 0]}	(5,5): {[0 0]}	

Upper:
 (0,0): {[0 1]}	(0,1): {[0 1]}	(0,2): {[1 0]}	(0,3): {}	(0,4): {}	(0,5): {}	
(1,0): {[0 1]}	(1,1): {[0 1]}	(1,2): {[0 1]}	(1,3): {[1 0]}	(1,4): {[1 0]}	(1,5): {[1 0]}	
(2,0): {[1 0]}	(2,1): {[0 1]}	(2,2): {[0 1]}	(2,3): {[0 1]}	(2,4): {[1 0]}	(2,5): {[1 0]}	
(3,0): {}	(3,1): {[1 0]}	(3,2): {[0 1]}	(3,3): {[0 1]}	(3,4): {[0 1]}	(3,5): {[1 0]}	
(4,0): {}	(4,1): {[1 0]}	(4,2): {[1 0]}	(4,3): {[0 1]}	(4,4): {[0 1]}	(4,5): {[0 1]}	
(5,0): {

In [10]:
# Test
L1_5 = L1 + L1
U1_5 = U1 + U1
print("L1+L1:\n",L1_5, "\nU1+U1:\n", U1_5)

L2 = L1_5 - U1
U2 = U1_5 - L1
print(L2,"\n", U2)

(0,0): {}	(0,1): {[0 1]}	(0,2): {[0 1],[ 1 -1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 0],[-1  2]}	(1,3): {[0 1],[ 1 -1]}	(1,4): {[0 1],[ 1 -1]}	(1,5): {[0 2],[1 0]}	
(2,0): {[0 1],[ 1 -1]}	(2,1): {[0 0],[-1  2]}	(2,2): {}	(2,3): {[0 0]}	(2,4): {[0 1]}	(2,5): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1],[ 1 -1]}	(3,2): {[0 0]}	(3,3): {}	(3,4): {[0 0]}	(3,5): {[0 1]}	
(4,0): {[1 0],[0 2]}	(4,1): {[0 1],[ 1 -1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {}	(4,5): {[0 0],[-1  2]}	
(5,0): {[1 1]}	(5,1): {[0 2],[1 0]}	(5,2): {[0 1]}	(5,3): {[0 1]}	(5,4): {[0 0],[-1  2]}	(5,5): {}	
 
 (0,0): {}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 0]}	(0,4): {[1 1]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 1],[ 1 -1]}	(1,3): {[0 2],[ 1 -1]}	(1,4): {[1 0]}	(1,5): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1],[ 1 -1]}	(2,2): {}	(2,3): {[0 1],[ 1 -1]}	(2,4): {[1 0],[0 2]}	(2,5): {[1 0]}	
(3,0): {[1 0]}	(3,1): {[0 2],[ 1 -1]}	(3,2): {[0 1],[ 1 -1]}	(3,3): {

In [17]:
class foo:
    bda = "C"
    
    def __init__(self):
        print("doit")

In [21]:
foo()

foo.bda = foo.bda+"C"

doit


In [23]:
foo.bda

'CC'