In [1]:
import Bounds as bds
import Bound as bd
import Table as tbl
import UpperBounds as ubds
import LowerBounds as lbds
import Robinson as Rob
import numpy as np

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
a = bd.Bound(ds = [1,2,3])
print(a)
b = bd.Bound(None,toCpy=a)
print("b: ", b)
d = a+b

c = (a+b).cpy()
print(a,c)

print(a <= c)
print(a >= c)

[1 2 3]
b:  [1 2 3]
[1 2 3] [2 4 6]
True
False


In [4]:
a3 = bd.Bound(ds= [2,4])
a2 = bd.Bound(ds= [3,2])
a1 = bd.Bound(ds =[2,2])
A_ = bds.Bounds()

A = lbds.LowerBounds(A_)
A.union(a1)
A.union(a2)
print(A)
B = lbds.LowerBounds(toCpy=A)
B.union(a3)
print(B)
#C = A.oMinusU(B)
#D = A.oPlusU(B)
#print(C, D)

{[3 2]}
{[3 2],[2 4]}


In [5]:
a1 = bd.Bound(ds= [2,4])
a2 = bd.Bound(ds= [3,2])
a3 = bd.Bound(ds =[2,2])
A = lbds.LowerBounds()
A.union(a1)
A.union(a2)
print(A)
B = ubds.UpperBounds()
B.union(a3)
print(B)
C = A - (B)
D = A + (B)
print(C, D)

{[2 4],[3 2]}
{[2 2]}
{[0 2],[1 0]} {[4 6],[5 4]}


In [6]:
T = [[A, B, C],
[None, B, C],
[None, None, C],
]

T = tbl.Table(withArray= T)

T.joinBoundsAt(0,0, D)
print(T)
len(T)
print(T.TypeTable())
# T + T

(0,0): {[4 6],[5 4]}	(0,1): {[2 2]}	(0,2): {[0 2],[1 0]}	
(1,0): {[2 2]}	(1,1): {[2 2]}	(1,2): {[0 2],[1 0]}	
(2,0): {[0 2],[1 0]}	(2,1): {[0 2],[1 0]}	(2,2): {[0 2],[1 0]}	

LowerBounds	UpperBounds	LowerBounds	
UpperBounds	UpperBounds	LowerBounds	
LowerBounds	LowerBounds	LowerBounds	



In [39]:
a = np.array([12,3,4])
print(a)
b = np.array(a)
print(b+1)
len(b)

[12  3  4]
[13  4  5]


3

In [5]:
class Test:
  def __init__(self):
    self.n = 3
  def __len__(self):
    return 7
  def dim(self):
    return 12

In [69]:
T = []
if not isinstance(T, list):
    
    raise Exception("withArray variable expects list, "+str(type(T))+" given.")


In [29]:
G = [ [ 2, 2, 1, 0, 0, 0 ],
      [ 2, 2, 2, 1, 1, 1 ],
      [ 1, 2, 2, 2, 1, 1 ],
      [ 0, 1, 2, 2, 2, 1 ],
      [ 0, 1, 1, 2, 2, 2 ],
      [ 0, 1, 1, 1, 2, 2 ] ]
R = Rob.Robinson(G,  k = 2)
R.find_embedding()

Within table
 (0,0): {}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 0]}	(0,4): {[1 1]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 1],[ 1 -1]}	(1,3): {[0 2],[ 1 -1]}	(1,4): {[1 0]}	(1,5): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1],[ 1 -1]}	(2,2): {}	(2,3): {[0 1],[ 1 -1]}	(2,4): {[1 0],[0 2]}	(2,5): {[1 0]}	
(3,0): {[1 0]}	(3,1): {[0 2],[ 1 -1]}	(3,2): {[0 1],[ 1 -1]}	(3,3): {}	(3,4): {[0 1],[ 1 -1]}	(3,5): {[0 1],[ 1 -1]}	
(4,0): {[1 1]}	(4,1): {[1 0]}	(4,2): {[1 0],[0 2]}	(4,3): {[0 1],[ 1 -1]}	(4,4): {}	(4,5): {[0 1],[ 1 -1]}	
(5,0): {[1 1]}	(5,1): {[1 0]}	(5,2): {[1 0]}	(5,3): {[0 1],[ 1 -1]}	(5,4): {[0 1],[ 1 -1]}	(5,5): {}	
 
Away table
 (0,0): {}	(0,1): {[0 1]}	(0,2): {[0 1],[ 1 -1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 0],[-1  2]}	(1,3): {[0 1],[ 1 -1]}	(1,4): {[0 1],[ 1 -1]}	(1,5): {[0 2],[1 0]}	
(2,0): {[0 1],[ 1 -1]}	(2,1): {[0 0],[-1  2]}	(2,2): {}	(2,3): {[0 0]}	(2,4): {[0 1]}	(2,5): {[0 1]}	
(3,0): {[1 0]}	(3,

In [35]:
G = [ [ 2, 2, 1, 0, 0 ],
      [ 2, 2, 2, 1, 1 ],
      [ 1, 2, 2, 2, 1 ],
      [ 0, 1, 2, 2, 2 ],
      [ 0, 1, 1, 2, 2 ] ]
R = Rob.Robinson(G,  k = 2)
R.find_embedding()

Within table
 (0,0): {}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 1]}	(0,4): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 1],[ 1 -1]}	(1,3): {[1 0],[0 2]}	(1,4): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1],[ 1 -1]}	(2,2): {}	(2,3): {[0 1]}	(2,4): {[1 0],[0 2]}	
(3,0): {[1 1]}	(3,1): {[1 0],[0 2]}	(3,2): {[0 1]}	(3,3): {}	(3,4): {[0 1],[ 1 -1]}	
(4,0): {[1 1]}	(4,1): {[1 0]}	(4,2): {[1 0],[0 2]}	(4,3): {[0 1],[ 1 -1]}	(4,4): {}	
 
Away table
 (0,0): {}	(0,1): {[0 0],[-1  2]}	(0,2): {[0 1],[ 1 -1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	
(1,0): {[0 0],[-1  2]}	(1,1): {}	(1,2): {[0 0]}	(1,3): {[0 1],[ 1 -1]}	(1,4): {[0 1],[ 1 -1]}	
(2,0): {[0 1],[ 1 -1]}	(2,1): {[0 0]}	(2,2): {}	(2,3): {[0 0]}	(2,4): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1],[ 1 -1]}	(3,2): {[0 0]}	(3,3): {}	(3,4): {[0 0]}	
(4,0): {[1 0],[0 2]}	(4,1): {[0 1],[ 1 -1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {}	

-------iter  1  ends-----
Within table
 (0,0): {}		(0,1): {[0 1],[-1  4]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 1],[0 3]}	(

KeyboardInterrupt: 

In [32]:
L1 = R.L_at(0)
U1 = R.U_at(0)
print(R.L_at(0))
#print(R.L_at(0).TypeTable())
print(R.U_at(0))
#print(R.U_at(0).TypeTable())

(0,0): {}	(0,1): {[0 0]}	(0,2): {[0 1]}	(0,3): {[1 0]}	(0,4): {[1 0]}	
(1,0): {[0 0]}	(1,1): {}	(1,2): {[0 0]}	(1,3): {[0 1]}	(1,4): {[0 1]}	
(2,0): {[0 1]}	(2,1): {[0 0]}	(2,2): {}	(2,3): {[0 0]}	(2,4): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1]}	(3,2): {[0 0]}	(3,3): {}	(3,4): {[0 0]}	
(4,0): {[1 0]}	(4,1): {[0 1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {}	

(0,0): {}	(0,1): {[0 1]}	(0,2): {[1 0]}	(0,3): {}	(0,4): {}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 1]}	(1,3): {[1 0]}	(1,4): {[1 0]}	
(2,0): {[1 0]}	(2,1): {[0 1]}	(2,2): {}	(2,3): {[0 1]}	(2,4): {[1 0]}	
(3,0): {}	(3,1): {[1 0]}	(3,2): {[0 1]}	(3,3): {}	(3,4): {[0 1]}	
(4,0): {}	(4,1): {[1 0]}	(4,2): {[1 0]}	(4,3): {[0 1]}	(4,4): {}	



In [33]:
L1_5 = L1 + L1
U1_5 = U1 + U1
print("L1+L1:\n",L1_5, "\nU1+U1:\n", U1_5)

L1+L1:
 (0,0): {}	(0,1): {[0 0]}	(0,2): {[0 1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	
(1,0): {[0 0]}	(1,1): {}	(1,2): {[0 0]}	(1,3): {[0 1]}	(1,4): {[0 1]}	
(2,0): {[0 1]}	(2,1): {[0 0]}	(2,2): {}	(2,3): {[0 0]}	(2,4): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1]}	(3,2): {[0 0]}	(3,3): {}	(3,4): {[0 0]}	
(4,0): {[1 0],[0 2]}	(4,1): {[0 1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {}	
 
U1+U1:
 (0,0): {}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 1]}	(0,4): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 1]}	(1,3): {[1 0],[0 2]}	(1,4): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1]}	(2,2): {}	(2,3): {[0 1]}	(2,4): {[1 0],[0 2]}	
(3,0): {[1 1]}	(3,1): {[1 0],[0 2]}	(3,2): {[0 1]}	(3,3): {}	(3,4): {[0 1]}	
(4,0): {[1 1]}	(4,1): {[1 0]}	(4,2): {[1 0],[0 2]}	(4,3): {[0 1]}	(4,4): {}	



In [10]:
L2 = L1_5 - U1
U2 = U1_5 - L1
print(L2,"\n", U2)

(0,0): {}	(0,1): {[0 1]}	(0,2): {[0 1],[ 1 -1]}	(0,3): {[1 0]}	(0,4): {[1 0],[0 2]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 0],[-1  2]}	(1,3): {[0 1],[ 1 -1]}	(1,4): {[0 1],[ 1 -1]}	(1,5): {[0 2],[1 0]}	
(2,0): {[0 1],[ 1 -1]}	(2,1): {[0 0],[-1  2]}	(2,2): {}	(2,3): {[0 0]}	(2,4): {[0 1]}	(2,5): {[0 1]}	
(3,0): {[1 0]}	(3,1): {[0 1],[ 1 -1]}	(3,2): {[0 0]}	(3,3): {}	(3,4): {[0 0]}	(3,5): {[0 1]}	
(4,0): {[1 0],[0 2]}	(4,1): {[0 1],[ 1 -1]}	(4,2): {[0 1]}	(4,3): {[0 0]}	(4,4): {}	(4,5): {[0 0],[-1  2]}	
(5,0): {[1 1]}	(5,1): {[0 2],[1 0]}	(5,2): {[0 1]}	(5,3): {[0 1]}	(5,4): {[0 0],[-1  2]}	(5,5): {}	
 
 (0,0): {}	(0,1): {[0 1]}	(0,2): {[1 0],[0 2]}	(0,3): {[1 0]}	(0,4): {[1 1]}	(0,5): {[1 1]}	
(1,0): {[0 1]}	(1,1): {}	(1,2): {[0 1],[ 1 -1]}	(1,3): {[0 2],[ 1 -1]}	(1,4): {[1 0]}	(1,5): {[1 0]}	
(2,0): {[1 0],[0 2]}	(2,1): {[0 1],[ 1 -1]}	(2,2): {}	(2,3): {[0 1],[ 1 -1]}	(2,4): {[1 0],[0 2]}	(2,5): {[1 0]}	
(3,0): {[1 0]}	(3,1): {[0 2],[ 1 -1]}	(3,2): {[0 1],[ 1 -1]}	(3,3): {

In [31]:
a